---
name: card_x_user
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
authors:
- Godzy EDK's
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^1.0.3
#  firebase_analytics: ^7.1.1
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.4
  firebase_core_platform_interface: ^4.0.0
  firebase_messaging: ^9.1.1
  firebase_in_app_messaging: ^0.4.0+1
  get: ^4.1.4
  get_storage: ^2.0.2
  google_sign_in: ^5.0.1
  splashscreen: ^1.3.5
  file_picker: ^3.0.1
  firebase_storage: ^8.0.3
  image_picker: ^0.7.4
#  linkedin_login: ^1.3.1
  editable: ^2.0.0
  apple_maps_flutter: ^1.0.0
  velocity_x: ^2.6.1
  flutter_sheet_localization: ^5.1.0
  agora_rtc_engine: ^3.3.3
  permission_handler: ^6.1.3
  font_awesome_flutter: ^9.0.0
  camera: ^0.8.1
  video_player: ^2.1.1
  arcore_flutter_plugin: ^0.0.10
  cupertino_icons: ^1.0.2
  optional: ^5.0.0+1
  model_viewer: ^0.8.1
  json_annotation: ^4.0.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  build_resolvers: ^2.0.0
  analyzer: ^1.4.0
  firebase_crashlytics: ^2.0.0
  integration_test:
    sdk: flutter
  e2e: ^0.7.0+1
  flutter_driver:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  firebase_messaging: ^9.1.1
  http:
  webview_flutter: ^2.0.4
  json_annotation: ^4.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/img/default.png
  - assets/img/defaultDark.png
  - assets/img/google_logo.png
  - assets/img/marlonW.jpg
  - assets/img/nunchaku.png
  - assets/AndroidRobot.gif
  - assets/Andy.svg.svg
  - assets/ArcticFox.gif
  - assets/copertina.jpg
  - assets/earth.jpg
  - assets/earth (2).jpg
  - assets/earth_augmented_image.jpg
  - assets/fox_face_mesh_texture.png
  - assets/myimages.imgdb
  - assets/prova_texture.png
  - assets/TocoToucan.gif
  - assets/topolino.jpg
  - assets/umano_digitale.png
  - assets/venom.jpg
  - assets/venom_with_eyes.jpg
flutter_intl:
  enabled: true
