name: card_x_user
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.15.0-42.0.dev <3.0.0'
  flutter: '>=1.22.6 <2.0.0'

dependencies: 
  splashscreen: ^1.3.5
  editable: ^2.0.0
  velocity_x: ^3.4.0
  flutter_sheet_localization: ^5.1.1
  permission_handler: ^9.2.0
  font_awesome_flutter: ^9.2.0
  video_player: ^2.3.0
  cupertino_icons: ^1.0.4
  optional: ^6.1.0+1
  model_viewer: ^0.8.1
  uuid: ^3.0.6
  getxfire: ^0.3.3
  file_picker: ^4.5.1
  get: ^4.6.1
  pokemon_tcg: 1.0.1
  fpdart: ^0.0.14
  scanbot_sdk: ^2.8.0
  nv_golden: ^1.0.1
  logging: ^1.0.2
  flag: ^6.0.0
  country_list_pick: 1.0.1+5
  get_storage: 2.0.3
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.7
  build_resolvers: ^2.0.6
  analyzer: ^3.3.1
  nv_golden: 1.0.1
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/img/default.png
    - assets/img/defaultDark.png
    - assets/img/google_logo.png
    - assets/img/marlonW.jpg
    - assets/img/pikachu.png
    - assets/earth.jpg
    - assets/earth (2).jpg
    - assets/earth_augmented_image.jpg
  uses-material-design: true

flutter_intl: 
  enabled: true

authors: 
  - Godzy EDK's

