---
name: card_x_user
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
authors:
- Godzy EDK's
environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.22.6 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_core_platform_interface: ^3.0.1
  firebase_messaging: ^7.0.3
  firebase_in_app_messaging: ^0.3.0+1
  fcm_config: ^2.0.0-dev.11
  get: ^3.24.0
  get_storage: ^1.4.0
  google_sign_in: ^4.5.9
  splashscreen: ^1.3.5
  file_picker: ^2.1.6
  firebase_storage: ^7.0.0
  http: ^0.12.2
  image_picker: ^0.6.7+22
  linkedin_login: ^1.3.1
  editable: ^1.1.3
  maps: ^0.4.3
  maps_adapter_google_maps: ^0.2.2
  apple_maps_flutter: ^0.1.3
  velocity_x: ^1.3.1
  flutter_sheet_localization: ^2.0.1
  simple_gravatar: null
  agora_rtc_engine: ^3.2.1
  permission_handler: ^5.1.0+2
  font_awesome_flutter: ^8.11.0
  camera: ^0.7.0+2
  video_player: ^1.0.1
  arcore_flutter_plugin: ^0.0.10
  cupertino_icons: ^1.0.2
  optional: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_sheet_localization_generator: ^2.1.2
  build_runner: ^1.10.12
  build_resolvers: ^1.5.2
  analyzer: ^0.39.0
  firebase_crashlytics: ^0.4.0+1
  integration_test:
    sdk: flutter
  e2e: ^0.7.0+1
  flutter_driver:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  analyzer: ^0.40.6
  firebase_core: ^0.7.0
  firebase_core_platform_interface: ^3.0.1
  firebase_messaging: ^8.0.0-dev.14
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/img/default.png
  - assets/img/defaultDark.png
  - assets/img/google_logo.png
  - assets/img/marlonW.jpg
  - assets/img/nunchaku.png
  - assets/AndroidRobot.gif
  - assets/Andy.svg.svg
  - assets/ArcticFox.gif
  - assets/copertina.jpg
  - assets/earth.jpg
  - assets/earth (2).jpg
  - assets/earth_augmented_image.jpg
  - assets/fox_face_mesh_texture.png
  - assets/myimages.imgdb
  - assets/prova_texture.png
  - assets/TocoToucan.gif
  - assets/topolino.jpg
  - assets/umano_digitale.png
  - assets/venom.jpg
  - assets/venom_with_eyes.jpg
flutter_intl:
  enabled: true
