name: card_x_user
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.15.0-42.0.dev <3.0.0'
  flutter: '>=1.22.6 <2.0.0'

dependencies: 
  google_sign_in: ^5.2.1
  splashscreen: ^1.3.5
  editable: ^2.0.0
  velocity_x: ^3.3.0
  flutter_sheet_localization: ^5.1.1
  permission_handler: ^8.3.0
  font_awesome_flutter: ^9.2.0
  video_player: ^2.2.7
  cupertino_icons: ^1.0.4
  optional: ^6.1.0+1
  model_viewer: ^0.8.1
  uuid: ^3.0.5
  getxfire: ^0.3.1
  file_picker: ^4.2.4
  get: 4.3.8
  get_storage: 2.0.3
  pokemon_tcg: 1.0.1
  fpdart: ^0.0.12
  scanbot_sdk: 2.6.0
  nv_golden: ^0.2.1
  logging: ^1.0.2
  flag: 5.0.1
  country_list_pick: 1.0.1+5
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.5
  build_resolvers: ^2.0.5
  analyzer: ^2.7.0
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/img/default.png
    - assets/img/defaultDark.png
    - assets/img/google_logo.png
    - assets/img/marlonW.jpg
    - assets/img/pikachu.png
    - assets/earth.jpg
    - assets/earth (2).jpg
    - assets/earth_augmented_image.jpg
  uses-material-design: true

flutter_intl: 
  enabled: true

authors: 
  - Godzy EDK's

