name: card_x_user
version: 1.0.0+1
publish_to: none
description: A new Flutter application.
environment: 
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.6 <2.0.0'

dependencies: 
  google_sign_in: ^5.0.7
  splashscreen: ^1.3.5
  editable: ^2.0.0
  velocity_x: ^3.3.0
  flutter_sheet_localization: ^5.1.1
  permission_handler: ^8.1.4+2
  font_awesome_flutter: ^9.1.0
  camera: ^0.9.2+1
  video_player: ^2.1.14
  cupertino_icons: ^1.0.3
  optional: ^6.1.0+1
  model_viewer: ^0.8.1
  uuid: ^3.0.4
  getxfire: 0.1.9
  file_picker: 4.0.0
  get: 4.3.8
  get_storage: 2.0.3
  pokemon_tcg: 1.0.1
  fpdart: 0.0.10
  scanbot_sdk: 2.6.0
  nv_golden: 0.1.1
  logging: 1.0.1
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.1
  build_resolvers: ^2.0.4
  analyzer: ^2.1.0
  flutter_test: 
    sdk: flutter
  integration_test: 
    sdk: flutter
  flutter_driver: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/img/default.png
    - assets/img/defaultDark.png
    - assets/img/google_logo.png
    - assets/img/marlonW.jpg
    - assets/img/nunchaku.png
    - assets/AndroidRobot.gif
    - assets/Andy.svg.svg
    - assets/ArcticFox.gif
    - assets/copertina.jpg
    - assets/earth.jpg
    - assets/earth (2).jpg
    - assets/earth_augmented_image.jpg
    - assets/fox_face_mesh_texture.png
    - assets/myimages.imgdb
    - assets/prova_texture.png
    - assets/TocoToucan.gif
    - assets/topolino.jpg
    - assets/umano_digitale.png
    - assets/venom.jpg
    - assets/venom_with_eyes.jpg
  uses-material-design: true

flutter_intl: 
  enabled: true

authors: 
  - Godzy EDK's

